FROM python:3.10

WORKDIR /app

# Install Recommender Webapp related modules and data
COPY ./embedders.py /app/
COPY ./recommender_webapp.py /app/
COPY ./docker/recommender_requirements.txt /app/
COPY ./data/mobilenet_dict /app/data/
COPY ./data/tfidf_1000.sav /app/data/
COPY ./data/posters/* /app/data/posters/

# Install python requirements
RUN pip install -r recommender_requirements.txt

# expose gradio port
EXPOSE 7860

# start service
ENTRYPOINT python recommender_webapp.py --docker

